version: "3.8"

services:
  app:
    image: americoallende/challenge-calc-service:latest
    container_name: challenge-calc-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/calcdb
      SPRING_DATASOURCE_USERNAME: calcuser
      SPRING_DATASOURCE_PASSWORD: calcpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - calc-net

  postgres:
    image: postgres:15
    container_name: challenge-calc-db
    restart: always
    environment:
      POSTGRES_DB: calcdb
      POSTGRES_USER: calcuser
      POSTGRES_PASSWORD: calcpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - calc-net

  redis:
    image: redis:7
    container_name: challenge-calc-redis
    ports:
      - "6379:6379"
    networks:
      - calc-net

volumes:
  pgdata:

networks:
  calc-net:
